services:
    jmz.phpbbcdn.listener:
        class: jmz\phpbbcdn\event\listener
        arguments:
            - @controller.helper
            - @template
            - @config
            - @user
        tags:
            - { name: event.listener }
